import { User } from './types';

export const mockUsers: (User & Record<'password', string>)[] = [
  {
    username: 'warehouseAdmin',
    password: 'Test_1234',
    email: 'warehouse@test.com',
    firstName: 'Warehouse',
    lastName: 'Admin',
  },
];

export const mockEvents = [
  {
    id: 2208,
    from: '2021-12-27T21:00:00.000Z',
    to: '2021-12-27T22:30:00.000Z',
    transportId: 'order_1v919',
    status: 'approved',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_1v919',
    e80w: null,
    truckLicensePlate: 'truckLP_3gfuu',
    trailerLicensePlate: 'trailerLP_43wl7',
    additionalInformation: 'Some additional information 63y55',
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-27T21:00:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input osoor',
  },
  {
    id: 2204,
    from: '2021-12-27T10:00:00.000Z',
    to: '2021-12-27T11:30:00.000Z',
    transportId: 'order_tngcd',
    status: 'requested',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_tngcd',
    e80w: null,
    truckLicensePlate: 'truckLP_4ogpw',
    trailerLicensePlate: 'trailerLP_ip1tb',
    additionalInformation: 'Some additional information l67ql',
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-27T10:00:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input ziv1q',
  },
  {
    id: 2202,
    from: '2021-12-27T08:30:00.000Z',
    to: '2021-12-27T10:00:00.000Z',
    transportId: 'order_s38oc',
    status: 'requested',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_s38oc',
    e80w: null,
    truckLicensePlate: 'truckLP_hysw1',
    trailerLicensePlate: 'trailerLP_eehyh',
    additionalInformation: 'Some additional information hod72',
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-27T08:30:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input ulwwn',
  },
  {
    id: 2192,
    from: '2021-12-27T07:00:00.000Z',
    to: '2021-12-27T08:30:00.000Z',
    transportId: 'order_rwjbw',
    status: 'requested',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_rwjbw',
    e80w: null,
    truckLicensePlate: 'truckLP_ybvrc',
    trailerLicensePlate: 'trailerLP_1uizh',
    additionalInformation: 'Some additional information zwwd2',
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-27T07:00:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input ytxa3',
  },
  {
    id: 2182,
    from: '2021-12-27T05:30:00.000Z',
    to: '2021-12-27T07:00:00.000Z',
    transportId: 'order_hnnyf',
    status: 'requested',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_hnnyf',
    e80w: null,
    truckLicensePlate: 'truckLP_nsq3c',
    trailerLicensePlate: 'trailerLP_s8933',
    additionalInformation: 'Some additional information e0af4',
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-27T05:30:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input 89cor',
  },
  {
    id: 2179,
    from: '2021-12-27T04:00:00.000Z',
    to: '2021-12-27T05:30:00.000Z',
    transportId: 'SocketTest1',
    status: 'requested',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'SocketTest1',
    e80w: null,
    truckLicensePlate: 'Truck',
    trailerLicensePlate: 'Trailer',
    additionalInformation: null,
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-27T04:00:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: null,
  },
  {
    id: 2163,
    from: '2021-12-27T02:30:00.000Z',
    to: '2021-12-27T04:00:00.000Z',
    transportId: 'SocketTest',
    status: 'declined',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'SocketTest',
    e80w: null,
    truckLicensePlate: null,
    trailerLicensePlate: 'Trailer2',
    additionalInformation: 'Declined',
    modificationId: 107,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-27T02:30:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: null,
  },
  {
    id: 2180,
    from: '2021-12-27T02:30:00.000Z',
    to: '2021-12-27T04:00:00.000Z',
    transportId: 'SocketTest2',
    status: 'approved',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'SocketTest2Modify',
    e80w: null,
    truckLicensePlate: null,
    trailerLicensePlate: null,
    additionalInformation: null,
    modificationId: 108,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-27T02:30:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: null,
  },
  {
    id: 2162,
    from: '2021-12-27T01:00:00.000Z',
    to: '2021-12-27T02:30:00.000Z',
    transportId: 'order_t93j3',
    status: 'requested',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_t93j3',
    e80w: null,
    truckLicensePlate: 'truckLP_d5hox',
    trailerLicensePlate: 'trailerLP_msofu',
    additionalInformation: 'Some additional information r4y0v',
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-27T01:00:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input kkt48',
  },
  {
    id: 2289,
    from: '2021-12-26T01:15:00.000Z',
    to: '2021-12-26T02:45:00.000Z',
    transportId: 'Byw1749Guest1',
    status: 'approved',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'Byw1749Guest1',
    e80w: null,
    truckLicensePlate: null,
    trailerLicensePlate: null,
    additionalInformation: 'sssss',
    modificationId: 140,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-26T01:00:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: null,
  },
  {
    id: 2296,
    from: '2021-12-25T20:00:00.000Z',
    to: '2021-12-25T20:30:00.000Z',
    transportId: 'Byw1749Guest3',
    status: 'registered',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: '2021-12-25T17:00:55.260Z',
    purchaseOrderId: 'Byw1749Guest3',
    e80w: null,
    truckLicensePlate: 'Byw1749Guest3',
    trailerLicensePlate: 'Byw1749Guest1',
    additionalInformation: null,
    modificationId: null,
    driverId: 1166,
    driverInfoId: 1165,
    scheduledFrom: '2021-12-25T17:00:55.260Z',
    scheduledTo: '2021-12-25T18:00:55.260Z',
    carrierCompany: {
      id: 134,
      companyName: 'Guest',
      contactEmail: 'none',
      contactPhone: null,
      companyNameSlug: 'guest',
      updatedAt: null,
    },
    carrierCompanyId: 134,
    ramp: {
      id: 22,
      name: 'Inbound_10',
      warehouseId: 1,
      loadingCapability: null,
      openingHoursFrom: '7',
      openingHoursTo: '17',
      activeEventId: null,
    },
    rampId: 22,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: null,
  },
  {
    id: 2292,
    from: '2021-12-25T17:45:00.000Z',
    to: '2021-12-25T18:45:00.000Z',
    transportId: 'Byw1749Booking3',
    status: 'done',
    loadingCapacity: 2,
    loadingDuration: 25,
    loadingStart: '2021-12-25T16:27:14.518Z',
    loadingEnd: '2021-12-25T16:27:39.032Z',
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: '2021-12-25T16:11:00.327Z',
    purchaseOrderId: 'Byw1749Booking3',
    e80w: null,
    truckLicensePlate: null,
    trailerLicensePlate: null,
    additionalInformation: null,
    modificationId: 139,
    driverId: 1164,
    driverInfoId: 1164,
    scheduledFrom: '2021-12-25T17:30:00.000Z',
    scheduledTo: '2021-12-25T18:30:00.000Z',
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'bbb',
  },
  {
    id: 2300,
    from: '2021-12-25T17:12:51.701Z',
    to: '2021-12-25T18:12:51.701Z',
    transportId: 'Byw1749Guest5',
    status: 'done',
    loadingCapacity: 2,
    loadingDuration: 25,
    loadingStart: '2021-12-25T17:13:37.326Z',
    loadingEnd: '2021-12-25T17:14:02.136Z',
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: '2021-12-25T17:12:51.701Z',
    purchaseOrderId: 'Byw1749Guest5',
    e80w: null,
    truckLicensePlate: 'Byw1749Guest5',
    trailerLicensePlate: 'Byw1749Guest5',
    additionalInformation: null,
    modificationId: null,
    driverId: 1169,
    driverInfoId: 1168,
    scheduledFrom: null,
    scheduledTo: null,
    carrierCompany: {
      id: 134,
      companyName: 'Guest',
      contactEmail: 'none',
      contactPhone: null,
      companyNameSlug: 'guest',
      updatedAt: null,
    },
    carrierCompanyId: 134,
    ramp: {
      id: 1,
      name: 'Inbound 1',
      warehouseId: 1,
      loadingCapability: '',
      openingHoursFrom: '7',
      openingHoursTo: '16',
      activeEventId: 2299,
    },
    rampId: 1,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: null,
  },
  {
    id: 2299,
    from: '2021-12-25T17:11:36.177Z',
    to: '2021-12-25T17:12:24.875Z',
    transportId: 'Byw1749Guest4',
    status: 'done',
    loadingCapacity: 1,
    loadingDuration: 49,
    loadingStart: '2021-12-25T17:11:36.177Z',
    loadingEnd: '2021-12-25T17:12:24.875Z',
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: '2021-12-25T17:07:23.033Z',
    purchaseOrderId: 'Byw1749Guest4',
    e80w: null,
    truckLicensePlate: 'Byw1749Guest4',
    trailerLicensePlate: 'Byw1749Guest4',
    additionalInformation: null,
    modificationId: null,
    driverId: 1168,
    driverInfoId: 1167,
    scheduledFrom: null,
    scheduledTo: null,
    carrierCompany: {
      id: 134,
      companyName: 'Guest',
      contactEmail: 'none',
      contactPhone: null,
      companyNameSlug: 'guest',
      updatedAt: null,
    },
    carrierCompanyId: 134,
    ramp: {
      id: 1,
      name: 'Inbound 1',
      warehouseId: 1,
      loadingCapability: '',
      openingHoursFrom: '7',
      openingHoursTo: '16',
      activeEventId: 2299,
    },
    rampId: 1,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: null,
  },
  {
    id: 2298,
    from: '2021-12-25T17:05:16.019Z',
    to: '2021-12-25T18:05:16.019Z',
    transportId: 'Byw1749Guest2',
    status: 'registered',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: '2021-12-25T17:05:16.019Z',
    purchaseOrderId: 'Byw1749Guest2',
    e80w: null,
    truckLicensePlate: 'Byw1749Guest2',
    trailerLicensePlate: 'Byw1749Guest2',
    additionalInformation: null,
    modificationId: null,
    driverId: 1167,
    driverInfoId: 1166,
    scheduledFrom: '2021-12-25T17:05:16.019Z',
    scheduledTo: '2021-12-25T18:05:16.019Z',
    carrierCompany: {
      id: 134,
      companyName: 'Guest',
      contactEmail: 'none',
      contactPhone: null,
      companyNameSlug: 'guest',
      updatedAt: null,
    },
    carrierCompanyId: 134,
    ramp: {
      id: 1,
      name: 'Inbound 1',
      warehouseId: 1,
      loadingCapability: '',
      openingHoursFrom: '7',
      openingHoursTo: '16',
      activeEventId: 2299,
    },
    rampId: 1,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: null,
  },
  {
    id: 2293,
    from: '2021-12-25T17:00:00.000Z',
    to: '2021-12-25T18:00:00.000Z',
    transportId: 'Byw1749Booking4',
    status: 'modified',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'Byw1749Booking4',
    e80w: null,
    truckLicensePlate: null,
    trailerLicensePlate: null,
    additionalInformation: null,
    modificationId: 141,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-25T17:00:00.000Z',
    scheduledTo: '2021-12-25T18:00:00.000Z',
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: null,
  },
  {
    id: 2291,
    from: '2021-12-25T14:00:00.000Z',
    to: '2021-12-25T15:00:00.000Z',
    transportId: 'Byw1749Booking2',
    status: 'registered',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: '2021-12-25T15:59:08.489Z',
    purchaseOrderId: 'Byw1749Booking2',
    e80w: null,
    truckLicensePlate: null,
    trailerLicensePlate: null,
    additionalInformation: null,
    modificationId: 138,
    driverId: 1163,
    driverInfoId: 1163,
    scheduledFrom: '2021-12-25T16:00:00.000Z',
    scheduledTo: '2021-12-25T17:00:00.000Z',
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: {
      id: 1,
      name: 'Inbound 1',
      warehouseId: 1,
      loadingCapability: '',
      openingHoursFrom: '7',
      openingHoursTo: '16',
      activeEventId: 2299,
    },
    rampId: 1,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'bbb',
  },
  {
    id: 2290,
    from: '2021-12-25T10:00:00.000Z',
    to: '2021-12-25T11:00:00.000Z',
    transportId: 'Byw1749Booking1',
    status: 'done',
    loadingCapacity: 2,
    loadingDuration: 32,
    loadingStart: '2021-12-25T14:34:41.152Z',
    loadingEnd: '2021-12-25T14:35:12.691Z',
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: '2021-12-25T08:34:16.282Z',
    purchaseOrderId: 'Byw1749Booking1',
    e80w: null,
    truckLicensePlate: null,
    trailerLicensePlate: null,
    additionalInformation: null,
    modificationId: 137,
    driverId: 1162,
    driverInfoId: 1162,
    scheduledFrom: '2021-12-25T08:00:00.000Z',
    scheduledTo: '2021-12-25T09:00:00.000Z',
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: {
      id: 1,
      name: 'Inbound 1',
      warehouseId: 1,
      loadingCapability: '',
      openingHoursFrom: '7',
      openingHoursTo: '16',
      activeEventId: 2299,
    },
    rampId: 1,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: null,
  },
  {
    id: 2152,
    from: '2021-12-25T08:30:00.000Z',
    to: '2021-12-25T10:00:00.000Z',
    transportId: 'order_zykxp',
    status: 'requested',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_zykxp',
    e80w: null,
    truckLicensePlate: 'truckLP_qfpui',
    trailerLicensePlate: 'trailerLP_md1l4',
    additionalInformation: 'Some additional information sh56o',
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-25T08:30:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input mbpwk',
  },
  {
    id: 2137,
    from: '2021-12-25T07:00:00.000Z',
    to: '2021-12-25T08:30:00.000Z',
    transportId: 'order_kytiz',
    status: 'requested',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_kytiz',
    e80w: null,
    truckLicensePlate: 'truckLP_0kz8z',
    trailerLicensePlate: 'trailerLP_b2ri2',
    additionalInformation: 'Some additional information 05ul7',
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-25T07:00:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input hbbe5',
  },
  {
    id: 2132,
    from: '2021-12-25T05:30:00.000Z',
    to: '2021-12-25T07:00:00.000Z',
    transportId: 'order_cyooc',
    status: 'requested',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_cyooc',
    e80w: null,
    truckLicensePlate: 'truckLP_4bxom',
    trailerLicensePlate: 'trailerLP_0zxrs',
    additionalInformation: 'Some additional information g1zq5',
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-25T05:30:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input nnrl0',
  },
  {
    id: 2131,
    from: '2021-12-25T04:00:00.000Z',
    to: '2021-12-25T05:30:00.000Z',
    transportId: '20DecBooking4',
    status: 'requested',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: '20DecBooking4',
    e80w: null,
    truckLicensePlate: null,
    trailerLicensePlate: null,
    additionalInformation: null,
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-25T04:00:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: null,
  },
  {
    id: 2252,
    from: '2021-12-24T12:03:57.402Z',
    to: '2021-12-24T13:03:57.402Z',
    transportId: 'truckLP_e83dg',
    status: 'registered',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: '2021-12-24T12:03:57.402Z',
    purchaseOrderId: 'truckLP_e83dg',
    e80w: null,
    truckLicensePlate: 'truckLP_e83dg',
    trailerLicensePlate: 'trailerLP_nupfe',
    additionalInformation: null,
    modificationId: null,
    driverId: 1145,
    driverInfoId: 1145,
    scheduledFrom: '2021-12-24T12:03:57.402Z',
    scheduledTo: '2021-12-24T13:03:57.402Z',
    carrierCompany: {
      id: 134,
      companyName: 'Guest',
      contactEmail: 'none',
      contactPhone: null,
      companyNameSlug: 'guest',
      updatedAt: null,
    },
    carrierCompanyId: 134,
    ramp: {
      id: 1,
      name: 'Inbound 1',
      warehouseId: 1,
      loadingCapability: '',
      openingHoursFrom: '7',
      openingHoursTo: '16',
      activeEventId: 2299,
    },
    rampId: 1,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: null,
  },
  {
    id: 2231,
    from: '2021-12-24T11:38:08.529Z',
    to: '2021-12-24T12:38:08.529Z',
    transportId: 'truckLP_41ogm',
    status: 'registered',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: '2021-12-24T11:38:08.529Z',
    purchaseOrderId: 'truckLP_41ogm',
    e80w: null,
    truckLicensePlate: 'truckLP_41ogm',
    trailerLicensePlate: 'trailerLP_x20nv',
    additionalInformation: null,
    modificationId: null,
    driverId: 1143,
    driverInfoId: 1143,
    scheduledFrom: '2021-12-24T11:38:08.529Z',
    scheduledTo: '2021-12-24T12:38:08.529Z',
    carrierCompany: {
      id: 134,
      companyName: 'Guest',
      contactEmail: 'none',
      contactPhone: null,
      companyNameSlug: 'guest',
      updatedAt: null,
    },
    carrierCompanyId: 134,
    ramp: {
      id: 1,
      name: 'Inbound 1',
      warehouseId: 1,
      loadingCapability: '',
      openingHoursFrom: '7',
      openingHoursTo: '16',
      activeEventId: 2299,
    },
    rampId: 1,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: null,
  },
  {
    id: 2220,
    from: '2021-12-24T10:11:42.469Z',
    to: '2021-12-24T11:11:42.469Z',
    transportId: 'truckLP_lyf87',
    status: 'registered',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: '2021-12-24T10:11:42.469Z',
    purchaseOrderId: 'truckLP_lyf87',
    e80w: null,
    truckLicensePlate: 'truckLP_lyf87',
    trailerLicensePlate: 'trailerLP_y4ddx',
    additionalInformation: null,
    modificationId: null,
    driverId: 1141,
    driverInfoId: 1141,
    scheduledFrom: '2021-12-24T10:11:42.469Z',
    scheduledTo: '2021-12-24T11:11:42.469Z',
    carrierCompany: {
      id: 134,
      companyName: 'Guest',
      contactEmail: 'none',
      contactPhone: null,
      companyNameSlug: 'guest',
      updatedAt: null,
    },
    carrierCompanyId: 134,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: null,
  },
  {
    id: 2130,
    from: '2021-12-24T08:30:00.000Z',
    to: '2021-12-24T10:00:00.000Z',
    transportId: '20DecBooking3',
    status: 'approved',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: '20DecBooking3',
    e80w: null,
    truckLicensePlate: null,
    trailerLicensePlate: null,
    additionalInformation: null,
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-24T08:00:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: null,
  },
  {
    id: 2129,
    from: '2021-12-24T06:30:00.000Z',
    to: '2021-12-24T08:00:00.000Z',
    transportId: '20DecBooking2',
    status: 'approved',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: '20DecBooking2',
    e80w: null,
    truckLicensePlate: null,
    trailerLicensePlate: null,
    additionalInformation: null,
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-24T06:30:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: null,
  },
  {
    id: 2111,
    from: '2021-12-24T05:00:00.000Z',
    to: '2021-12-24T06:30:00.000Z',
    transportId: 'order_rdgjq',
    status: 'requested',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_rdgjq',
    e80w: null,
    truckLicensePlate: 'truckLP_va9xd',
    trailerLicensePlate: 'trailerLP_q6br5',
    additionalInformation: 'Some additional information 7c7m2',
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-24T05:00:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input 3qnt5',
  },
  {
    id: 2109,
    from: '2021-12-24T03:30:00.000Z',
    to: '2021-12-24T05:00:00.000Z',
    transportId: 'order_6cz2t',
    status: 'requested',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_6cz2t',
    e80w: null,
    truckLicensePlate: 'truckLP_21x2b',
    trailerLicensePlate: 'trailerLP_h6j3l',
    additionalInformation: 'Some additional information ooujm',
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-24T03:30:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input n9nhb',
  },
  {
    id: 2100,
    from: '2021-12-24T02:00:00.000Z',
    to: '2021-12-24T03:30:00.000Z',
    transportId: 'order_ti70j',
    status: 'requested',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_ti70j',
    e80w: null,
    truckLicensePlate: 'truckLP_h98hq',
    trailerLicensePlate: 'trailerLP_54vsr',
    additionalInformation: 'Some additional information koew3',
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-24T02:00:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input uvvr5',
  },
  {
    id: 2099,
    from: '2021-12-24T00:30:00.000Z',
    to: '2021-12-24T02:00:00.000Z',
    transportId: 'order_k4rd4',
    status: 'approved',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_k4rd4',
    e80w: null,
    truckLicensePlate: 'truckLP_spf1f',
    trailerLicensePlate: 'trailerLP_0kkep',
    additionalInformation: 'Some additional information gk9h4',
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-24T00:30:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input 54muy',
  },
  {
    id: 2081,
    from: '2021-12-22T22:30:00.000Z',
    to: '2021-12-23T00:00:00.000Z',
    transportId: 'order_ecbf3',
    status: 'modified',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_ecbf3',
    e80w: null,
    truckLicensePlate: 'truckLP_1c7me',
    trailerLicensePlate: 'trailerLP_hgf5l',
    additionalInformation: 'Some additional information 4dg9u',
    modificationId: 78,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-22T22:30:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input ko0f4',
  },
  {
    id: 2080,
    from: '2021-12-22T21:15:00.000Z',
    to: '2021-12-22T22:45:00.000Z',
    transportId: 'order_2u8zf',
    status: 'approved',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_2u8zf',
    e80w: null,
    truckLicensePlate: 'truckLP_2amqt',
    trailerLicensePlate: 'trailerLP_1woae',
    additionalInformation: 'Some additional information a6nzm',
    modificationId: 77,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-22T21:00:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input sbrsq',
  },
  {
    id: 2176,
    from: '2021-12-22T06:07:30.899Z',
    to: '2021-12-22T06:09:06.947Z',
    transportId: '22DecGuest1',
    status: 'done',
    loadingCapacity: 1,
    loadingDuration: 96,
    loadingStart: '2021-12-22T06:07:30.899Z',
    loadingEnd: '2021-12-22T06:09:06.947Z',
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: '2021-12-22T05:40:06.478Z',
    purchaseOrderId: '22DecGuest1',
    e80w: null,
    truckLicensePlate: '22DecGuest1',
    trailerLicensePlate: '22DecGuest1',
    additionalInformation: null,
    modificationId: null,
    driverId: 1134,
    driverInfoId: 1134,
    scheduledFrom: '2021-12-22T05:40:06.478Z',
    scheduledTo: '2021-12-22T06:40:06.478Z',
    carrierCompany: {
      id: 134,
      companyName: 'Guest',
      contactEmail: 'none',
      contactPhone: null,
      companyNameSlug: 'guest',
      updatedAt: null,
    },
    carrierCompanyId: 134,
    ramp: {
      id: 1,
      name: 'Inbound 1',
      warehouseId: 1,
      loadingCapability: '',
      openingHoursFrom: '7',
      openingHoursTo: '16',
      activeEventId: 2299,
    },
    rampId: 1,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: null,
  },
  {
    id: 2079,
    from: '2021-12-21T09:30:00.000Z',
    to: '2021-12-21T11:00:00.000Z',
    transportId: 'order_wl39w',
    status: 'modified',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_wl39w',
    e80w: null,
    truckLicensePlate: 'truckLP_rds4u',
    trailerLicensePlate: 'trailerLP_0mnec',
    additionalInformation: 'Some additional information upgah',
    modificationId: 76,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-21T09:30:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input 3k36d',
  },
  {
    id: 2078,
    from: '2021-12-21T08:00:00.000Z',
    to: '2021-12-21T09:30:00.000Z',
    transportId: 'order_me1fp',
    status: 'modified',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_me1fp',
    e80w: null,
    truckLicensePlate: 'truckLP_c6p8b',
    trailerLicensePlate: 'trailerLP_pqznp',
    additionalInformation: 'Some additional information fuym3',
    modificationId: 75,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-21T08:00:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input c3mr3',
  },
  {
    id: 2077,
    from: '2021-12-21T06:30:00.000Z',
    to: '2021-12-21T08:00:00.000Z',
    transportId: 'order_3whpq',
    status: 'registered',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: '2021-12-22T05:54:58.488Z',
    purchaseOrderId: 'order_3whpq',
    e80w: null,
    truckLicensePlate: 'truckLP_3ui2j_ncEdit',
    trailerLicensePlate: 'trailerLP_tnzu3_ncEdit',
    additionalInformation: 'Some additional information eo8t9_ncEdit',
    modificationId: null,
    driverId: 1135,
    driverInfoId: 1135,
    scheduledFrom: '2021-12-21T06:30:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: {
      id: 1,
      name: 'Inbound 1',
      warehouseId: 1,
      loadingCapability: '',
      openingHoursFrom: '7',
      openingHoursTo: '16',
      activeEventId: 2299,
    },
    rampId: 1,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input iad7s_ncEdit',
  },
  {
    id: 2076,
    from: '2021-12-21T05:00:00.000Z',
    to: '2021-12-21T06:30:00.000Z',
    transportId: 'order_5rwcs',
    status: 'approved',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_5rwcs',
    e80w: null,
    truckLicensePlate: 'truckLP_zh10i',
    trailerLicensePlate: 'trailerLP_0i0wb',
    additionalInformation: 'Some additional information dihat',
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-21T05:00:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input gwqc0',
  },
  {
    id: 2082,
    from: '2021-12-21T03:00:00.000Z',
    to: '2021-12-21T04:30:00.000Z',
    transportId: 'order_e3x4m',
    status: 'requested',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_e3x4m',
    e80w: null,
    truckLicensePlate: 'truckLP_ggd6y',
    trailerLicensePlate: 'trailerLP_8n5s2',
    additionalInformation: 'Some additional information 55gns',
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-21T03:00:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input rxh9p',
  },
  {
    id: 2075,
    from: '2021-12-21T01:30:00.000Z',
    to: '2021-12-21T03:00:00.000Z',
    transportId: 'order_g0nea',
    status: 'requested',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_g0nea',
    e80w: null,
    truckLicensePlate: 'truckLP_6te0b_ncEdit',
    trailerLicensePlate: 'trailerLP_z74ty_ncEdit',
    additionalInformation: 'Some additional information kkqcf_ncEdit',
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-21T01:30:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input dzgai_ncEdit',
  },
  {
    id: 2074,
    from: '2021-12-21T00:00:00.000Z',
    to: '2021-12-21T01:30:00.000Z',
    transportId: 'order_3ntjb',
    status: 'modified',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_3ntjb',
    e80w: null,
    truckLicensePlate: 'truckLP_h0tew',
    trailerLicensePlate: 'trailerLP_rmhpl',
    additionalInformation: 'Some additional information s9je2',
    modificationId: 74,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-21T00:00:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input lyfd3',
  },
  {
    id: 2073,
    from: '2021-12-20T22:30:00.000Z',
    to: '2021-12-21T00:00:00.000Z',
    transportId: 'order_y8ox3',
    status: 'approved',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_y8ox3',
    e80w: null,
    truckLicensePlate: 'truckLP_ubqsz',
    trailerLicensePlate: 'trailerLP_drwgi',
    additionalInformation: 'Some additional information gjb7c',
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-20T22:30:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input tezga',
  },
  {
    id: 2068,
    from: '2021-12-20T21:00:00.000Z',
    to: '2021-12-20T22:30:00.000Z',
    transportId: 'order_gkali',
    status: 'requested',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_gkali',
    e80w: null,
    truckLicensePlate: 'truckLP_5qdug',
    trailerLicensePlate: 'trailerLP_dh8q3',
    additionalInformation: 'Some additional information n6l8w',
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-20T21:00:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input 3k9fg',
  },
  {
    id: 2127,
    from: '2021-12-20T17:43:04.876Z',
    to: '2021-12-20T17:43:29.842Z',
    transportId: '20DecGuest1',
    status: 'done',
    loadingCapacity: 1,
    loadingDuration: 25,
    loadingStart: '2021-12-20T17:43:04.876Z',
    loadingEnd: '2021-12-20T17:43:29.842Z',
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: '2021-12-20T17:29:05.129Z',
    purchaseOrderId: '20DecGuest1',
    e80w: null,
    truckLicensePlate: '20DecGuest1',
    trailerLicensePlate: '20DecGuest1',
    additionalInformation: null,
    modificationId: null,
    driverId: 1127,
    driverInfoId: 1127,
    scheduledFrom: '2021-12-20T17:29:05.129Z',
    scheduledTo: '2021-12-20T18:29:05.129Z',
    carrierCompany: {
      id: 134,
      companyName: 'Guest',
      contactEmail: 'none',
      contactPhone: null,
      companyNameSlug: 'guest',
      updatedAt: null,
    },
    carrierCompanyId: 134,
    ramp: {
      id: 1,
      name: 'Inbound 1',
      warehouseId: 1,
      loadingCapability: '',
      openingHoursFrom: '7',
      openingHoursTo: '16',
      activeEventId: 2299,
    },
    rampId: 1,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: null,
  },
  {
    id: 2071,
    from: '2021-12-20T09:30:00.000Z',
    to: '2021-12-20T11:00:00.000Z',
    transportId: 'order_hk06b',
    status: 'modified',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_hk06b',
    e80w: null,
    truckLicensePlate: 'truckLP_nxfwu',
    trailerLicensePlate: 'trailerLP_tbnuh',
    additionalInformation: 'Some additional information oaszw',
    modificationId: 72,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-20T09:30:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input zwr0c',
  },
  {
    id: 2126,
    from: '2021-12-20T08:48:20.736Z',
    to: '2021-12-20T09:48:20.736Z',
    transportId: 'LOL123A',
    status: 'registered',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: '2021-12-20T08:48:20.736Z',
    purchaseOrderId: 'LOL123A',
    e80w: null,
    truckLicensePlate: 'LOL123A',
    trailerLicensePlate: 'LOL123A',
    additionalInformation: null,
    modificationId: null,
    driverId: 1126,
    driverInfoId: 1126,
    scheduledFrom: '2021-12-20T08:48:20.736Z',
    scheduledTo: '2021-12-20T09:48:20.736Z',
    carrierCompany: {
      id: 134,
      companyName: 'Guest',
      contactEmail: 'none',
      contactPhone: null,
      companyNameSlug: 'guest',
      updatedAt: null,
    },
    carrierCompanyId: 134,
    ramp: {
      id: 2,
      name: 'Inbound 2',
      warehouseId: 1,
      loadingCapability: '',
      openingHoursFrom: '7',
      openingHoursTo: '16',
      activeEventId: null,
    },
    rampId: 2,
    warehouseId: 1,
    loadingType: {
      id: 4,
      name: 'Importas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 4,
    returnTrip: false,
    loadInput: null,
  },
  {
    id: 2125,
    from: '2021-12-20T08:43:35.407Z',
    to: '2021-12-20T09:43:35.407Z',
    transportId: 'LOPO',
    status: 'registered',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: '2021-12-20T08:43:35.407Z',
    purchaseOrderId: 'LOPO',
    e80w: null,
    truckLicensePlate: 'LOP',
    trailerLicensePlate: 'LOP',
    additionalInformation: null,
    modificationId: null,
    driverId: 1125,
    driverInfoId: 1125,
    scheduledFrom: '2021-12-20T08:43:35.407Z',
    scheduledTo: '2021-12-20T09:43:35.407Z',
    carrierCompany: {
      id: 134,
      companyName: 'Guest',
      contactEmail: 'none',
      contactPhone: null,
      companyNameSlug: 'guest',
      updatedAt: null,
    },
    carrierCompanyId: 134,
    ramp: {
      id: 1,
      name: 'Inbound 1',
      warehouseId: 1,
      loadingCapability: '',
      openingHoursFrom: '7',
      openingHoursTo: '16',
      activeEventId: 2299,
    },
    rampId: 1,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: null,
  },
  {
    id: 2072,
    from: '2021-12-20T08:00:00.000Z',
    to: '2021-12-20T09:30:00.000Z',
    transportId: 'order_js23l',
    status: 'modified',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_js23l',
    e80w: null,
    truckLicensePlate: 'truckLP_zqy09',
    trailerLicensePlate: 'trailerLP_zgeva',
    additionalInformation: 'Some additional information yfei9',
    modificationId: 73,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-20T08:00:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input s3eqy',
  },
  {
    id: 2070,
    from: '2021-12-20T08:00:00.000Z',
    to: '2021-12-20T09:30:00.000Z',
    transportId: 'order_2bl4u',
    status: 'declined',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_2bl4u',
    e80w: null,
    truckLicensePlate: 'truckLP_er4w1',
    trailerLicensePlate: 'trailerLP_o7hv2',
    additionalInformation: 'Declined by integration test',
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-20T08:00:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input yu3n1',
  },
  {
    id: 2069,
    from: '2021-12-20T06:30:00.000Z',
    to: '2021-12-20T08:00:00.000Z',
    transportId: 'order_9lvsq',
    status: 'approved',
    loadingCapacity: null,
    loadingDuration: null,
    loadingStart: null,
    loadingEnd: null,
    rampFree: null,
    estimatedArrivalTime: null,
    actualArrivalTime: null,
    purchaseOrderId: 'order_9lvsq',
    e80w: null,
    truckLicensePlate: 'truckLP_l1y3q_ncEdit',
    trailerLicensePlate: 'trailerLP_p6pqg_ncEdit',
    additionalInformation: 'Some additional information x382l_ncEdit',
    modificationId: null,
    driverId: null,
    driverInfoId: null,
    scheduledFrom: '2021-12-20T06:30:00.000Z',
    scheduledTo: null,
    carrierCompany: {
      id: 131,
      companyName: 'FantasyLogistics',
      contactEmail: 'info@byways.io',
      contactPhone: '+491737623260',
      companyNameSlug: 'fantasylogistics',
      updatedAt: null,
    },
    carrierCompanyId: 131,
    ramp: null,
    rampId: null,
    warehouseId: 1,
    loadingType: {
      id: 3,
      name: 'Eksportas & some ',
      comment: 'testressource',
    },
    loadingTypeId: 3,
    returnTrip: false,
    loadInput: 'Load input x8ylk_ncEdit',
  },
];
